### ISSUE TITLE
Hydrolox Configuration

### ISSUE THREAD

**Issue by Tyaedalis** [ferram4/ProcEngines#2]
This is for discussion about the Hydrolox configuration.

To start things off, some words concerning this from @ferram4:
> I'd go for lower O/F ratios, actually. Hydrolox engines tend to run really fuel-rich, and their preburners/gas generators even more so, so I'd take the O/F down to 0.1 at least. Maybe a little lower. As for the high end, 204 is probably a little extreme; I believe the numbers, but I know that no engine has ever run that O/F at any condition, so you can probably pick a lower range to start off with.
> 
> Tell you what, start by going up to ~20, and if needed we can fill in the higher range later and limit hydrolox to fuel-rich only. Your optimal range should be from ~4-6, and the performance should be nice and smooth through there.

However, I am having trouble calculating the values for anything under about 0.3 O/F. I followed the (very thorough) instructions multiple times, starting from scratch. Any ideas?

### Parameters:
- **O/F range**: 0.5–20
- **Optimal O/F range**: 4.5–6.5
- **Frozen Area Ratio**: 3
- **Pressure range**: 0.25–100 MPa

### O/F Values to Calculate:

- [x] 0.5
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 4.5
- [x] 4.75
- [x] 5
- [x] 5.25
- [x] 5.5
- [x] 5.7
- [x] 5.8
- [x] 5.9
- [x] 6
- [x] 6.1
- [x] 6.2
- [x] 6.3
- [x] 6.5
- [x] 7
- [x] 10
- [x] 15
- [x] 20

(Wondering if these are adequate.)

**Comment by ferram4** [comment]
Looking at it myself, I think that what's happening is that there isn't enough energy for sufficiently gaseous products.  [Based on the master's thesis](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&sqi=2&ved=0ahUKEwibtMDyo7TVAhUBVT4KHQMyBfIQFggkMAA&url=https%3A%2F%2Frepository.tudelft.nl%2Fislandora%2Fobject%2Fuuid%3Ae2cda6d2-e3ff-4809-a62a-80c250146413%2Fdatastream%2FOBJ%2Fdownload&usg=AFQjCNG-pLO4NMNoBw_HGhSHDAI8s3nCWg) that I'm basing a lot of this on, It sets the min O/F for LH2/LOX at 0.5, so I'd put it at 0.5 and abandon anything below that.  It gets below the desired temp anyway.

For pressure, I'd have it range from 0.25 MPa to 100 MPa.

**Comment by ferram4** [comment]
So, criticisms:
The optimal O/F range should be extended downward a bit; we'll need detailed data down to around 4.5 at least.  The lowest ratio I know of is 4.8 for the J-2 in its high-efficiency, low-thrust mode (variable mix ratios, woo).

So far it looks good.  I'd check how the chamber temps vary between O/F = 0.5 and O/F = 2 to see if another point needs to be there, but otherwise it looks good.

**Comment by Tyaedalis** [comment]
It's so helpful to know what kind of data you are looking for exactly. So,
thanks for helping me help you!

**Comment by ferram4** [comment]
Oh, wait.  I see an error, a pretty critical one:  You're grabbing the wrong molecular weight.  There are two molecular weights read out in RPA, one labelled MW and one labelled M.  You should take the one labelled M since it has a higher number of significant figures.  I think I forgot to make the distinction in the tutorial text since I was hoping it would be clear through the picture.  I'll make sure to modify tutorial to account for that.

Sorry about the hassle, this is my fault for not being specific enough.

**Comment by Tyaedalis** [comment]
Ah, I should have asked about that. The config labels it `MW` so I just assumed it would be the same. Fortunately, I've gotten pretty quick at generating these (I can probably do about 3 O/F blocks in 20 minutes now). These first attempts will probably be a bit shaky, but my process will just keep improving with time.

Another question, since this may come up later anyway: should I worry about ever changing the frozen area ratio?

I feel like I'm asking a lot of questions, but it is rocket science, after all!

**Comment by ferram4** [comment]
Frozen area ratio should probably be increased; I think the recommended one for hydrolox is around 3 or so from what the literature says.  Kerolox has a relatively low number; I think keeping it at 3 or maybe dropping it to 2.0-2.5 for other values probably makes sense.  Unfortunately, testing it in RPA and picking a numbr that doesn't change the outcome much isn't viable, because it can actually change the outcome a fair bit.

Please, ask away.  You're the one volunteering your time for tedious data entry, it's worthwhile to make sure it's right.

**Comment by Tyaedalis** [comment]
I think I'll continue on my way, then, using a frozen area ratio of 3 for this config, then use 2.2 for the others (if I do more). I'm gonna try to get this hydrolox data (properly now) all entered in the next hour or so. I just happen to have a lot of free time at the moment, and what better way to spend it than improving one of my favorite pastimes?

**Comment by ferram4** [comment]
Closed by #4
